version: "3"
services:
  nodejs-server:
    container_name: nodejs_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app/api
        - /usr/src/app/api/node_modules
  vue-ui:
    container_name: vue_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/app/client
        - /usr/src/app/client/node_modules
    links:
      - nodejs-server
